name: CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build
      
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.1.0
      with:
        # The connection string for the storage account
        connection_string: ${{ secrets.AZ_STORAGE }}
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The name of the directory you want to upload
        source_dir: 'build'
        # Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`
        sync: true
        # Use `az storage blob sync` to synchronize blobs recursively
        #sync: # optional
